apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # Defines which pods are going to be represented by this service
  # This service becomes network endpoint for either other services or external users (e.g. browsers)
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      # Used to be nodePort but changed to targetPort when type changed from NodePort to LoadBalancer
      # Also original port of 30080 didn't work so changed to 80
      targetPort: 80
  # Was originally NodePort but couldn't get it to work with GKE so changed to LoadBalancer
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP

